<configuration>
  <property>
    <name>dfs.ha.automatic-failover.enabled</name>
    <value>true</value>
  </property>

  <property>
    <name>dfs.nameservice.id</name>
    <value>analytics-ha</value>
  </property>

  <property>
    <name>dfs.nameservices</name>
    <value>hdfs</value>
  </property>

  <property>
    <name>dfs.ha.namenodes.analytics-ha</name>
    <value>nn1,nn2</value>
  </property>

  <property>
    <name>dfs.namenode.rpc-address.analytics-ha.nn1</name>
    <value>192.168.51.103:50070</value>
  </property>

  <property>
    <name>dfs.namenode.http-address.analytics-ha.nn2</name>
    <value>192.168.51.104:50070</value>
  </property>

  <property>
    <name>dfs.client.failover.proxy.provider.analytics-ha</name>
    <value>org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider</value>
  </property>
</configuration>